//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ejemplo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ca_ClasificacionJuzgados
    {
        public short id_ClasificacionJuzgado { get; set; }
        public short Id_Partido { get; set; }
        public Nullable<short> No_Juzgado { get; set; }
        public string nombre_Juzgado { get; set; }
        public string partido_Judicial { get; set; }
        public string municipio { get; set; }
        public string Localidad { get; set; }
        public System.DateTime Fecha_Registro { get; set; }
        public Nullable<short> Usu_Act { get; set; }
        public Nullable<System.DateTime> Fecha_Act { get; set; }
    }
}
