//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ejemplo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ca_Delitos
    {
        public short Id_Clasificacion { get; set; }
        public short Id_Grupo { get; set; }
        public short Id_Delito { get; set; }
        public string Id_Delito2 { get; set; }
        public string Descripcion { get; set; }
        public Nullable<byte> Gravedad { get; set; }
        public Nullable<short> Usu_Act { get; set; }
        public Nullable<System.DateTime> Fecha_Act { get; set; }
    }
}
