//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ejemplo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ca_Domicilios
    {
        public int id_Domicilio { get; set; }
        public string entidad_Federativa { get; set; }
        public string municipio { get; set; }
        public string localidad { get; set; }
        public string colonia { get; set; }
        public Nullable<int> Id_Tipo_Vialidad { get; set; }
        public string calle { get; set; }
        public Nullable<byte> Id_Tipo_Carretera { get; set; }
        public string Descripcion_Vialidad { get; set; }
        public string numero { get; set; }
        public Nullable<int> codigo_Postal { get; set; }
        public System.DateTime fecha_Registro { get; set; }
        public Nullable<System.DateTime> Fecha_Act { get; set; }
        public Nullable<short> Usu_Act { get; set; }
    }
}
