//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ejemplo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ca_PreguntasFrecuentes
    {
        public byte Id_Pregunta { get; set; }
        public Nullable<byte> TipoPregunta { get; set; }
        public string Pregunta { get; set; }
        public string Respuesta { get; set; }
        public Nullable<short> Usu_act { get; set; }
        public Nullable<System.DateTime> Fecha_Act { get; set; }
    }
}
