//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ejemplo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class de_Bitacora
    {
        public short Anio { get; set; }
        public int Id_Expediente { get; set; }
        public short Id_Consec { get; set; }
        public string accion { get; set; }
        public Nullable<byte> Id_Estatus { get; set; }
        public System.DateTime fecha_Registro { get; set; }
        public string Acta_Anterior { get; set; }
        public string Acta_Actual { get; set; }
        public string Averiguacion_Previa_Anterio { get; set; }
        public string Averiguacion_Previa_Actual { get; set; }
        public Nullable<System.DateTime> Fecha_APrevia_Anterior { get; set; }
        public string numero_Expediente_Anterior { get; set; }
        public string numero_Expediente_Actual { get; set; }
        public Nullable<int> Id_DPM_Anterior { get; set; }
        public Nullable<int> Id_DPM_Actual { get; set; }
        public Nullable<int> Id_DPJ_Anterior { get; set; }
        public Nullable<int> Id_DPJ_Actual { get; set; }
        public Nullable<int> Id_Acusado { get; set; }
        public Nullable<short> Usu_Act { get; set; }
        public Nullable<System.DateTime> Fecha_Act { get; set; }
    }
}
