//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ejemplo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class De_Delitos
    {
        public short Anio { get; set; }
        public int Id_Expediente { get; set; }
        public string Id_Delito2 { get; set; }
        public int Id_Ofendido { get; set; }
        public byte Id_Tipo { get; set; }
        public int Id_Acusado { get; set; }
        public byte Id_Tipo_Defensor { get; set; }
        public Nullable<short> Usu_Act { get; set; }
        public Nullable<System.DateTime> Fecha_Act { get; set; }
    }
}
