//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ejemplo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class De_Expedientes_Archivos
    {
        public short Anio { get; set; }
        public int Id_Expediente { get; set; }
        public string Id_AccionProcesal { get; set; }
        public short id_Archivo { get; set; }
        public int Id_Persona { get; set; }
        public Nullable<byte> Id_Rol { get; set; }
        public Nullable<byte> Tipo_Archivo { get; set; }
        public string Nombre_Archivo { get; set; }
        public string Nombre_Archivo_Original { get; set; }
        public string Mime_Type { get; set; }
        public string tamanio_Archivo { get; set; }
        public System.DateTime fecha_Registro { get; set; }
        public Nullable<short> Usu_Act { get; set; }
        public Nullable<System.DateTime> Fecha_Act { get; set; }
    }
}
