//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ejemplo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class De_Expedientes_AccionesProcesales
    {
        public short Anio { get; set; }
        public int id_Expediente { get; set; }
        public string id_AccionProcesal { get; set; }
        public int Id_Persona { get; set; }
        public short consecutivo { get; set; }
        public string comentario { get; set; }
        public string Comentario_Seguimiento { get; set; }
        public System.DateTime fecha_Registro { get; set; }
        public Nullable<short> Usu_Act { get; set; }
        public Nullable<System.DateTime> Fecha_Act { get; set; }
    }
}
