//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ejemplo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs
    {
        public int Id_Error { get; set; }
        public string Cookie { get; set; }
        public string Ex_Message { get; set; }
        public string Ex_Inner { get; set; }
        public string Ex_Source { get; set; }
        public string username { get; set; }
        public string Ex_StackTrace { get; set; }
        public string Valor1 { get; set; }
        public string Valor2 { get; set; }
        public string Valor3 { get; set; }
        public string Valor4 { get; set; }
        public string Fecha { get; set; }
    }
}
