//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ejemplo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ta_Parametros
    {
        public short Id_Parametro { get; set; }
        public Nullable<int> Id_Expediente_Max { get; set; }
        public string Descrip { get; set; }
        public string Directorio { get; set; }
        public string InfoContacto { get; set; }
        public string Telefonos { get; set; }
        public string CorreoElectronico { get; set; }
        public string CorreoEnvia { get; set; }
        public string Domicilio { get; set; }
        public string Titulo { get; set; }
    }
}
