//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ejemplo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCa_Roles
    {
        public byte id_Rol { get; set; }
        public string nombre_Rol { get; set; }
        public Nullable<System.DateTime> Fecha_Act { get; set; }
        public Nullable<short> Usu_Act { get; set; }
        public string Usuario { get; set; }
    }
}
