//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ejemplo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCa_Tipo_Cierre
    {
        public int Id_Tipo_Cierre { get; set; }
        public Nullable<byte> Id_Tipo_Defensor { get; set; }
        public Nullable<byte> Id_Tipo { get; set; }
        public string Descripcion { get; set; }
        public string TIPO { get; set; }
        public Nullable<short> Usu_Act { get; set; }
        public Nullable<System.DateTime> Fecha_Act { get; set; }
        public string Usuario { get; set; }
    }
}
