//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ejemplo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCa_Personas
    {
        public int Id_Persona { get; set; }
        public Nullable<byte> Id_Tipo_Persona { get; set; }
        public string Tipo_Persona { get; set; }
        public string curp { get; set; }
        public string nombre { get; set; }
        public string primer_Apellido { get; set; }
        public string segundo_Apellido { get; set; }
        public string NombreCompleto { get; set; }
        public Nullable<int> id_Domicilio { get; set; }
        public string Domicilio { get; set; }
        public string Cedula_Profesional { get; set; }
        public Nullable<short> Id_Parentesco { get; set; }
        public string Parentesco { get; set; }
        public string Telefono { get; set; }
        public System.DateTime fecha_Registro { get; set; }
        public Nullable<short> Usu_Act { get; set; }
        public Nullable<System.DateTime> Fecha_Act { get; set; }
        public string Usuario { get; set; }
        public string entidad_Federativa { get; set; }
        public string municipio { get; set; }
        public string localidad { get; set; }
        public string colonia { get; set; }
        public string calle { get; set; }
        public string numero { get; set; }
        public Nullable<int> codigo_Postal { get; set; }
        public Nullable<int> Id_Tipo_Vialidad { get; set; }
        public Nullable<byte> Id_Tipo_Carretera { get; set; }
        public string Descripcion_Vialidad { get; set; }
        public Nullable<bool> Nacionalidad { get; set; }
        public string Descripcion_Nacionalidad { get; set; }
        public string NacionalidadDesc { get; set; }
        public string alias { get; set; }
    }
}
