//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ejemplo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCa_Usuarios
    {
        public int id_Usuario { get; set; }
        public string NombreCompleto { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public bool activo { get; set; }
        public System.DateTime fecha_Registro { get; set; }
        public Nullable<short> Usu_Act { get; set; }
        public Nullable<System.DateTime> Fecha_Act { get; set; }
        public string nombre_Rol { get; set; }
        public string CURP { get; set; }
        public Nullable<byte> Id_Rol { get; set; }
        public Nullable<int> Id_Sector { get; set; }
        public string Sector { get; set; }
        public Nullable<int> Id_Juzgado { get; set; }
        public string nombre_Juzgado { get; set; }
        public string PartidoJudicial { get; set; }
    }
}
