//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ejemplo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vLoginCiudadano
    {
        public short Anio { get; set; }
        public int Id_Expediente { get; set; }
        public int Id_Persona { get; set; }
        public string nombre { get; set; }
        public string primer_Apellido { get; set; }
        public string segundo_Apellido { get; set; }
        public string NombreCompleto { get; set; }
        public string curp { get; set; }
        public string numero_Expediente { get; set; }
        public string Acta { get; set; }
        public string Averiguacion_Previa { get; set; }
        public string Clave_Expediente { get; set; }
    }
}
