//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ejemplo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vMa_Expedientes
    {
        public short Anio { get; set; }
        public int id_Expediente { get; set; }
        public string numero_Expediente { get; set; }
        public string Acta { get; set; }
        public Nullable<System.DateTime> fecha_Entrada { get; set; }
        public string Averiguacion_Previa { get; set; }
        public Nullable<System.DateTime> Fecha_APrevia { get; set; }
        public Nullable<bool> grave { get; set; }
        public Nullable<bool> detenido { get; set; }
        public Nullable<bool> orden_Aprension { get; set; }
        public Nullable<System.DateTime> fecha_Consignacion { get; set; }
        public string notas { get; set; }
        public System.DateTime fecha_Registro { get; set; }
        public string Id_AccionProcesal { get; set; }
        public short Id_ClasificacionJuzgado { get; set; }
        public string ClasificacionJuzgado_Nombre { get; set; }
        public int id_Acusado { get; set; }
        public int id_Ofendido { get; set; }
        public int id_Familiar { get; set; }
        public int id_DefPubMinisterial { get; set; }
        public string DPM_Nombre { get; set; }
        public int id_Coadyugante { get; set; }
        public int id_DefPubJuzgado { get; set; }
        public string DPJ_Nombre { get; set; }
        public int id_Juez { get; set; }
        public int id_Secretaria { get; set; }
        public Nullable<short> Usu_Act { get; set; }
        public Nullable<System.DateTime> Fecha_Act { get; set; }
        public string Familiar_CURP { get; set; }
        public string Familiar_Nombre { get; set; }
        public string Familiar_Ape1 { get; set; }
        public string Familiar_Ape2 { get; set; }
        public Nullable<int> Familiar_Id_Domicilio { get; set; }
        public string Familiar_Tel { get; set; }
        public Nullable<byte> Familiar_Id_Tipo_Persona { get; set; }
        public Nullable<int> Familiar_Nacionalidad { get; set; }
        public string Familiar_Descripcion_Nacionalidad { get; set; }
        public Nullable<short> Familiar_Id_Parentesco { get; set; }
        public string Familiar_Parentesco { get; set; }
        public string Familiar_Entidad { get; set; }
        public string Familiar_Mpio { get; set; }
        public string Familiar_Local { get; set; }
        public string Familiar_Colonia { get; set; }
        public string Familiar_Calle { get; set; }
        public string Familiar_NoExt { get; set; }
        public Nullable<int> Familiar_CP { get; set; }
        public Nullable<int> Familiar_Id_Tipo_Vialidad { get; set; }
        public Nullable<byte> Familiar_Id_Tipo_Carretera { get; set; }
        public string Familiar_Descripcion_Vialidad { get; set; }
        public Nullable<byte> Coadyugante_Id_Tipo_Persona { get; set; }
        public string Coadyugante_CURP { get; set; }
        public string Coadyugante_Nombre { get; set; }
        public string Coadyugante_Ape1 { get; set; }
        public string Coadyugante_Ape2 { get; set; }
        public Nullable<int> Coadyugante_Id_Domicilio { get; set; }
        public string Coadyugante_Cedula { get; set; }
        public string Coadyugante_Tel { get; set; }
        public Nullable<int> Coadyugante_Nacionalidad { get; set; }
        public string Coadyugante_Descripcion_Nacionalidad { get; set; }
        public string Coadyugante_Entidad { get; set; }
        public string Coadyugante_Mpio { get; set; }
        public string Coadyugante_Local { get; set; }
        public string Coadyugante_Colonia { get; set; }
        public string Coadyugante_Calle { get; set; }
        public string Coadyugante_NoExt { get; set; }
        public Nullable<int> Coadyugante_CP { get; set; }
        public Nullable<int> Coadyugante_Id_Tipo_Vialidad { get; set; }
        public Nullable<byte> Coadyugante_Id_Tipo_Carretera { get; set; }
        public string Coadyugante_Descripcion_Vialidad { get; set; }
        public string Juez_CURP { get; set; }
        public string Juez_Nombre { get; set; }
        public string Juez_Ape1 { get; set; }
        public string Juez_Ape2 { get; set; }
        public string Secretaria_CURP { get; set; }
        public string Secretaria_Nombre { get; set; }
        public string Secretaria_Ape1 { get; set; }
        public string Secretaria_Ape2 { get; set; }
        public string AccionProcesal { get; set; }
        public string Usuario { get; set; }
        public Nullable<int> id_Representante { get; set; }
        public string Representante_Nombre { get; set; }
        public string Id_AccionProcesal_Siguiente { get; set; }
        public string Comentario_AccionProcesal_Siguiente { get; set; }
        public string Archivo_AccionProcesal_Siguiente { get; set; }
        public string ArchivoOriginal_AccionProcesal_Siguiente { get; set; }
        public string AccionProcesalSiguiente { get; set; }
        public Nullable<byte> Id_Estatus { get; set; }
        public Nullable<byte> Id_Sector_PGJ { get; set; }
        public string Sector_PGJ { get; set; }
        public Nullable<System.DateTime> Fecha_Radicacion { get; set; }
        public Nullable<byte> Id_Partido_Judicial { get; set; }
        public Nullable<short> Id_Etapa_Procesal { get; set; }
        public Nullable<byte> Id_SubEtapa_Procesal { get; set; }
        public Nullable<byte> Id_Accion { get; set; }
        public string Notas_DPJ { get; set; }
        public Nullable<bool> Grave_DPJ { get; set; }
        public string Clave_Expediente { get; set; }
        public Nullable<byte> Cierre_Defensoria { get; set; }
        public string tituloEstatus { get; set; }
        public string descripEstatus { get; set; }
    }
}
