//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ejemplo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSeguimientoProceso
    {
        public short Anio { get; set; }
        public int id_Expediente { get; set; }
        public int Id_Persona { get; set; }
        public string fecha_Registro { get; set; }
        public System.DateTime FechaRegistro2 { get; set; }
        public string AccionProcesal { get; set; }
        public string NotaArchivo { get; set; }
        public Nullable<byte> Id_Tipo_Persona { get; set; }
        public string curp { get; set; }
        public string nombre { get; set; }
        public string primer_Apellido { get; set; }
        public string segundo_Apellido { get; set; }
        public Nullable<int> id_Domicilio { get; set; }
        public string Cedula_Profesional { get; set; }
        public Nullable<short> Id_Parentesco { get; set; }
        public string Telefono { get; set; }
        public Nullable<bool> Nacionalidad { get; set; }
        public string Descripcion_Nacionalidad { get; set; }
        public System.DateTime Fecha_Registro_Persona { get; set; }
        public Nullable<short> Usu_Act { get; set; }
        public Nullable<System.DateTime> Fecha_Act { get; set; }
        public string alias { get; set; }
        public string id_AccionProcesal { get; set; }
        public short consecutivo { get; set; }
        public Nullable<byte> Id_Estado_Comparescencia_DPM { get; set; }
        public Nullable<byte> Id_Estado_Comparescencia_DPJ { get; set; }
        public string EstadoComparecencia { get; set; }
        public string SituacionJuridica { get; set; }
        public string Juzgado { get; set; }
    }
}
